---
apiVersion: v1
kind: Namespace
metadata:
  name: vs-test
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vs-test-db
  namespace: vs-test
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vs-test-db
  template:
    metadata:
      labels:
        app: vs-test-db
    spec:
      containers:
        - name: vs-test-db
          resources:
            limits:
              cpu: 0.2
              memory: 200M
          image: 'timms/postgres-logging:10.3'
          imagePullPolicy: Always
          ports:
            - name: vs-test-db
              containerPort: 5432
          env:
            - name: POSTGRES_USER
              value: 'vstester'
            - name: PGPASSWORD
              value: 'rootpw'
            - name: POSTGRES_DB
              value: 'vstest'
---
apiVersion: v1
kind: Service
metadata:
  name: vs-test-db
  namespace: vs-test
spec:
  type: NodePort
  selector:
    app: vs-test-db
  ports:
    - name: vs-test-db
      port: 5432
      targetPort: 5432
      protocol: TCP
